# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Llama3.3 70B Instruct model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-3.3-70B-Instruct --ignore-patterns "original/consolidated*" --output-dir /tmp/Llama-3.3-70B-Instruct
#
# To launch on 8 devices, run the following command from root:
#   tune run --nproc_per_node 8 full_finetune_distributed --config llama3_3/70B_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nproc_per_node 8 full_finetune_distributed --config llama3_3/70B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config is only tested on an 8xA100 machine.
#

output_dir: /tmp/torchtune/llama3_3_70B/full_dpo # /tmp may be deleted by your system. Change it to your preference.
base_dir: BASE_DIR_PLACEHOLDER # Change this to your base directory where the model is stored
wand_entity: WANDB_ENTITY_PLACEHOLDER # Change this to your WandB entity

# Parallelism
# tensor_parallel_dim: 1
# tensor_parallel_plan:
#   _component_: torchtune.models.llama3.base_llama_tp_plan

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ${base_dir}/meta-llama/Llama-3.3-70B-Instruct/original/tokenizer.model
  max_seq_len: 1024 # higher increases memory

# Model Arguments
model:
  _component_: torchtune.models.llama3_3.llama3_3_70b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${base_dir}/meta-llama/Llama-3.3-70B-Instruct/
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: "00030"
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3

# The ref_checkpointer should always point to the original weights.
ref_checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ${base_dir}/meta-llama/Llama-3.3-70B-Instruct/
  checkpoint_files:
    filename_format: model-{}-of-{}.safetensors
    max_filename: "00030"
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: LLAMA3

resume_from_checkpoint: False
# enable_async_checkpointing: True

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.preference_dataset
  source: json
  data_files: data/preference_Llama-3.3-70B-Instruct_dpo_NaiveCompletion_randpos_synthetic_alpaca.json
  packed: False  # True increases speed
  split: train
seed: null
shuffle: True

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  weight_decay: 0.0
  lr: 1.0e-5
lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 0

loss:
  _component_: torchtune.rlhf.loss.DPOLoss
  beta: 0.1  # default value is 0.1
  label_smoothing: 0  # default value is 0

# Training
epochs: 1
batch_size: 1
max_steps_per_epoch: null
gradient_accumulation_steps: 32  # Use to increase effective batch size
clip_grad_norm: 1.0

# Memory management
device: cuda
enable_activation_checkpointing: True  # True reduces memory
enable_activation_offloading: True  # True reduces memory
custom_sharded_layers: ['tok_embeddings', 'output']  # Layers to shard separately (useful for large vocab size models). Lower Memory, but lower speed.
# fsdp_cpu_offload: True
compile: False  # torch.compile the model + loss, True increases speed + decreases memory

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  project: secalign
  entity: ${wand_entity}
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: True
log_level: INFO  # DEBUG, WARN, etc.



# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
